config/routes.rb
Rails.application.routes.draw do
  get 'not_found/index'
  get 'administrator_profile/index'
  patch 'administrator_profile/update'
  get 'portfolio_manager_profile/index'
  patch 'portfolio_manager_profile/update'
  get 'trader_profile/index'
  patch 'trader_profile/update'
  get 'welcome/index'
  root 'welcome#index'
  get 'not_authorized/index'
  # resources :portfolio_managers
  resources :administrators

  post 'sessions/create'
  get 'sessions/destroy'

  get 'trading/index'
  get 'trading/autocomplete/:q', to: 'trading#autocomplete_symbol'
  get 'trading/getIntraPrices', to: 'trading#getIntraPrices'
  post 'trading/addFavoriteStock', to: 'trading#add_favorite_stock', via: :post, as: :add_favorite_stock
  post 'trading/removeFavoriteStock', to: 'trading#remove_favorite_stock', via: :delete, as: :remove_favorite_stock

   # resources :traders
  # get 'traders/index'

  resources :sessions, only: %i[new create destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :portfolio_managers do
    resources :traders
  end
end

app/models/administrator.rb
class Administrator < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/intraday_price.rb
class IntradayPrice
    attr_accessor :date, :open, :high, :low, :close, :volume
end

app/models/pm_profile.rb
class PmProfile < ApplicationRecord
  belongs_to :user
  
  validates :investment_strategy, length: { maximum: 50 }
  validates :ips, length: { maximum: 50 }
  validates :pm_notes, length: { maximum: 300 }  
end

app/models/portfolio_manager.rb
class PortfolioManager < User
end

app/models/service_result.rb
class ServiceResult
  attr_reader :succeeded, :errorMessage, :data

  def initialize(succeeded, errorMessage)
    @succeeded = succeeded
    @errorMessage = errorMessage
  end

  def initialize(succeeded)
    @succeeded = succeeded
  end

  def initialize; end

  def setAsSuccessful(data)
    @succeeded = true
    @data = data
    return self
  end

  def setAsFailed(errorMessage)
    @succeeded = false
    @errorMessage = errorMessage
    return self
  end
end

app/models/stock_price_info.rb
class StockPriceInfo
    attr_accessor :close, :dividends, :high, :low, :open, :stockSplits, :volume,
    :previousClose, :marketCap, :peRatio, :epsRatio, :dividendYield, :lastDividendValue, :averageVolume, :bid, :ask, :yield
end

app/models/stock_symbol.rb
class StockSymbol < ApplicationRecord
    has_many :trader_stocks, dependent: :destroy
    has_many :users, through: :trader_stocks
end

app/models/trader.rb
class Trader < User
 
end

app/models/trader_profile.rb
class TraderProfile < ApplicationRecord
  belongs_to :user

  validates :preferred_index1, length: { maximum: 50 }
  validates :preferred_index2, length: { maximum: 50 }
  validates :preferred_index3, length: { maximum: 50 }
  validates :trader_notes, length: { maximum: 300 }
end

app/models/trader_stock.rb
class TraderStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock_symbol
end

app/models/user.rb
class User < ApplicationRecord
  include PasswordValidable
  include UserFieldsValidable
  include AccountNameInitializable
  include UserProfileImageSeteable

  has_many :traders, class_name: 'Trader',
                     foreign_key: 'portfolio_manager_id',
                     dependent: :delete_all

  belongs_to :portfolio_manager, class_name: 'PortfolioManager', optional: true

  has_many :trader_stocks, dependent: :destroy
  has_many :stocks, through: :trader_stocks, source: :stock_symbol
  has_one :pm_profile, dependent: :destroy
  accepts_nested_attributes_for   :pm_profile
  has_one :trader_profile, dependent: :destroy
  accepts_nested_attributes_for :trader_profile
end

app/controllers/portfolio_managers_controller.rb
class PortfolioManagersController < ApplicationController
  before_action only: %i[index new create destroy edit update] do verify_user_access(['Administrator']) end
  before_action only: %i[show] do verify_user_access(%w[Administrator PortfolioManager]) end
  before_action only: %i[show] do verify_user_requestor_is_logged_in('PortfolioManager', params[:id]) end
  before_action :set_portfolio_manager, only: %i[show edit update destroy]

  # GET /portfolio_managers or /portfolio_managers.json
  def index
    @portfolio_managers = PortfolioManager.all
  end

  # GET /portfolio_managers/1 or /portfolio_managers/1.json
  def show; end

  # GET /portfolio_managers/new
  def new
    @portfolio_manager = PortfolioManager.new
  end

  # GET /portfolio_managers/1/edit
  def edit; end

  # POST /portfolio_managers or /portfolio_managers.json
  def create
    @portfolio_manager = PortfolioManager.new(portfolio_manager_params)

    respond_to do |format|
      if @portfolio_manager.save
        format.html do
          redirect_to portfolio_managers_url, notice: 'Portfolio manager was successfully created.'
        end
        # format.json { render :show, status: :created, location: @portfolio_manager }
      else
        format.html { render :new, status: :unprocessable_entity }
        # format.json { render json: @portfolio_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolio_managers/1 or /portfolio_managers/1.json
  def update
    respond_to do |format|
      if @portfolio_manager.update(portfolio_manager_params)
        format.html do
          redirect_to portfolio_managers_url, notice: 'Portfolio manager was successfully updated.'
        end
        # format.json { render :show, status: :ok, location: @portfolio_manager }
      else
        format.html { render :edit, status: :unprocessable_entity }
        # format.json { render json: @portfolio_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolio_managers/1 or /portfolio_managers/1.json
  def destroy
    @portfolio_manager.destroy

    respond_to do |format|
      format.html { redirect_to portfolio_managers_url, notice: 'Portfolio manager was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.

  def set_portfolio_manager
    @portfolio_manager = PortfolioManager.find_by(id: params[:id])

    return if @portfolio_manager.present?

    redirect_to not_found_index_url
  end

  # Only allow a list of trusted parameters through.
  def portfolio_manager_params
    params.require(:portfolio_manager).permit(:first_name, :last_name, :email, :password)
  end
end

app/controllers/trader_controller.rb
class TraderController < ApplicationController
  def index
    require 'uri'
    require 'net/http'
    require 'openssl'
    
    url = URI(ENV["STOCK_PRICES_API_URL"])

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    request = Net::HTTP::Get.new(url)
    request["X-RapidAPI-Key"] = ENV["STOCK_PRICES_API_KEY"]
    request["X-RapidAPI-Host"] = ENV["STOCK_PRICES_API_HOST"]

    response = http.request(request)
    body = response.read_body   
    hash = JSON.parse(body)

    @close= hash[hash.keys[0]]["Close"]
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/not_found_helper.rb
module NotFoundHelper
end

app/helpers/portfolio_managers_helper.rb
module PortfolioManagersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/traders_helper.rb
module TradersHelper
end

app/helpers/trading_helper.rb
module TradingHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/portfolio_managers/_admin_portfolio_managers.html.erb
<h1>Portfolio Managers</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @portfolio_managers.each do |portfolio_manager| %>
      <tr>
        <td><%= portfolio_manager.first_name %></td>
        <td><%= portfolio_manager.last_name %></td>
        <td><%= portfolio_manager.email %></td>
        <td>
          <div>
            <%= link_to "Show", portfolio_manager_path(id: portfolio_manager.id) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "New Portfolio Manager", new_portfolio_manager_path %>

app/views/portfolio_managers/_form.html.erb
<%= form_with(model: portfolio_manager) do |form| %>
  <% if portfolio_manager.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(portfolio_manager.errors.count, "error") %> prohibited this portfolio_manager from being saved:</h2>
      <ul>
        <% portfolio_manager.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="p-2 d-flex flex-column">
    <div class="form-group">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, class:"form-control",placeholder:"First name"  %>
    </div>
    <div class="form-group">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, class:"form-control",placeholder:"Last name"  %>
    </div>
    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, class:"form-control",placeholder:"Emails"  %>
    </div>
    <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, class:"form-control",placeholder:"Password"  %>
    </div>
    <div class="d-flex flex-row">
      <% if isAdmin %>
        <div class="p-2 form-group">
          <%= link_to "Cancel", portfolio_managers_path , class:"btn btn-secondary"%>
        </div>
      <% end %>
      <div class="p-2 form-group">
        <%= form.submit :Submit, :value => "Save", class:"btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/portfolio_managers/_portfolio_manager.html.erb
<div id="<%= dom_id portfolio_manager %>">
  <div class="form-group row">
    <label for="firstName" class="col-sm-2 col-form-label">First name</label>
    <div class="col-sm-4">
      <input  class="form-control" type="text" readonly id="firstName" value="<%= portfolio_manager.first_name %>">
    </div>
  </div>
  <div class="form-group row">
    <label for="lastName" class="col-sm-2 col-form-label">Last name</label>
    <div class="col-sm-4">
      <input  class="form-control" type="text" readonly id="lastName" value="<%= portfolio_manager.last_name %>">
    </div>
  </div>
  <div class="form-group row">
    <label for="email" class="col-sm-2 col-form-label">Email</label>
    <div class="col-sm-4">
      <input  class="form-control" type="text" readonly id="email" value="<%= portfolio_manager.email %>">
    </div>
  </div>
</div>

app/views/portfolio_managers/edit.html.erb
<h1>Editing portfolio manager</h1>
<%= render "form", portfolio_manager: @portfolio_manager %>

app/views/portfolio_managers/index.html.erb
<p style="color: green" data-attr="pm index"><%= notice %></p>
<h1>Portfolio managers</h1>
<div id="portfolio_managers">
  <%= link_to "Add new", new_portfolio_manager_path,  class: "btn btn-primary" %>
  <table class="mt-2 table">
    <thead>
      <tr>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Email</th>
        <th scope="col">Command</th>
      </tr>
    </thead>
    <tbody>
      <% @portfolio_managers.each do |portfolio_manager| %>
        <tr>
          <td><%= portfolio_manager.first_name %></td>
          <td><%= portfolio_manager.last_name %></td>
          <td><%= portfolio_manager.email %></td>
          <td>
            <%= link_to "Show", portfolio_manager,  class: "btn btn-outline-primary"  %>          
            <%= link_to 'Edit', edit_portfolio_manager_path(portfolio_manager),  class: "btn btn-outline-primary" %>
            <%= link_to "Remove",[portfolio_manager], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                },   class: "btn btn-outline-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/portfolio_managers/new.html.erb
<h1>New portfolio manager</h1>
<%= render "form", portfolio_manager: @portfolio_manager %>

app/views/portfolio_managers/show.html.erb
<p style="color: green" data-attr="pm show"><%= notice %></p>

<h1>Portfolio Manager</h1>
<div class="mb-2">
   <%= render @portfolio_manager %>
  <% if isAdmin %>
 
    <%= link_to "Back to portfolio managers", portfolio_managers_path, class:"btn btn-secondary" %>
  <%end%>
</div>
<%= render "traders/portfolio_managers_traders"%>