config/routes.rb
Rails.application.routes.draw do
  get 'not_found/index'
  get 'administrator_profile/index'
  patch 'administrator_profile/update'
  get 'portfolio_manager_profile/index'
  patch 'portfolio_manager_profile/update'
  get 'trader_profile/index'
  patch 'trader_profile/update'
  get 'welcome/index'
  root 'welcome#index'
  get 'not_authorized/index'
  # resources :portfolio_managers
  resources :administrators

  post 'sessions/create'
  get 'sessions/destroy'

  get 'trading/index'
  get 'trading/autocomplete/:q', to: 'trading#autocomplete_symbol'
  get 'trading/getIntraPrices', to: 'trading#getIntraPrices'
  post 'trading/addFavoriteStock', to: 'trading#add_favorite_stock', via: :post, as: :add_favorite_stock
  post 'trading/removeFavoriteStock', to: 'trading#remove_favorite_stock', via: :delete, as: :remove_favorite_stock

   # resources :traders
  # get 'traders/index'

  resources :sessions, only: %i[new create destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :portfolio_managers do
    resources :traders
  end
end

app/models/administrator.rb
class Administrator < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/intraday_price.rb
class IntradayPrice
    attr_accessor :date, :open, :high, :low, :close, :volume
end

app/models/pm_profile.rb
class PmProfile < ApplicationRecord
  belongs_to :user
  
  validates :investment_strategy, length: { maximum: 50 }
  validates :ips, length: { maximum: 50 }
  validates :pm_notes, length: { maximum: 300 }  
end

app/models/portfolio_manager.rb
class PortfolioManager < User
end

app/models/service_result.rb
class ServiceResult
  attr_reader :succeeded, :errorMessage, :data

  def initialize(succeeded, errorMessage)
    @succeeded = succeeded
    @errorMessage = errorMessage
  end

  def initialize(succeeded)
    @succeeded = succeeded
  end

  def initialize; end

  def setAsSuccessful(data)
    @succeeded = true
    @data = data
    return self
  end

  def setAsFailed(errorMessage)
    @succeeded = false
    @errorMessage = errorMessage
    return self
  end
end

app/models/stock_price_info.rb
class StockPriceInfo
    attr_accessor :close, :dividends, :high, :low, :open, :stockSplits, :volume,
    :previousClose, :marketCap, :peRatio, :epsRatio, :dividendYield, :lastDividendValue, :averageVolume, :bid, :ask, :yield
end

app/models/stock_symbol.rb
class StockSymbol < ApplicationRecord
    has_many :trader_stocks, dependent: :destroy
    has_many :users, through: :trader_stocks
end

app/models/trader.rb
class Trader < User
 
end

app/models/trader_profile.rb
class TraderProfile < ApplicationRecord
  belongs_to :user

  validates :preferred_index1, length: { maximum: 50 }
  validates :preferred_index2, length: { maximum: 50 }
  validates :preferred_index3, length: { maximum: 50 }
  validates :trader_notes, length: { maximum: 300 }
end

app/models/trader_stock.rb
class TraderStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock_symbol
end

app/models/user.rb
class User < ApplicationRecord
  include PasswordValidable
  include UserFieldsValidable
  include AccountNameInitializable
  include UserProfileImageSeteable

  has_many :traders, class_name: 'Trader',
                     foreign_key: 'portfolio_manager_id',
                     dependent: :delete_all

  belongs_to :portfolio_manager, class_name: 'PortfolioManager', optional: true

  has_many :trader_stocks, dependent: :destroy
  has_many :stocks, through: :trader_stocks, source: :stock_symbol
  has_one :pm_profile, dependent: :destroy
  accepts_nested_attributes_for   :pm_profile
  has_one :trader_profile, dependent: :destroy
  accepts_nested_attributes_for :trader_profile
end

app/controllers/trader_controller.rb
class TraderController < ApplicationController
  def index
    require 'uri'
    require 'net/http'
    require 'openssl'
    
    url = URI(ENV["STOCK_PRICES_API_URL"])

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    request = Net::HTTP::Get.new(url)
    request["X-RapidAPI-Key"] = ENV["STOCK_PRICES_API_KEY"]
    request["X-RapidAPI-Host"] = ENV["STOCK_PRICES_API_HOST"]

    response = http.request(request)
    body = response.read_body   
    hash = JSON.parse(body)

    @close= hash[hash.keys[0]]["Close"]
  end
end

app/controllers/traders_controller.rb
class TradersController < ApplicationController
  before_action { verify_user_access(%w[Administrator PortfolioManager]) }
  before_action :set_portfolio_manager, only: %i[index new edit create update destroy]
  before_action only: %i[index new edit create update destroy] do
    verify_user_requestor_is_logged_in('PortfolioManager', params[:portfolio_manager_id])
  end
  # before_action :set_trader, only: %i[update destroy]

  # GET /traders or /traders.json
  def index
    # @portfolio_manager = PortfolioManager.find(current_user.id)
    @traders = @portfolio_manager.traders
  end

  # GET /traders/1 or /traders/1.json
  # def show; end

  # GET /traders/new
  def new
    @trader = Trader.new
  end

  # GET /traders/1/edit
  def edit
    @trader = @portfolio_manager.traders.find(params[:id])
  end

  # POST /traders or /traders.json
  def create
    # @portfolio_manager = PortfolioManager.find(params[:portfolio_manager_id])
    @trader = @portfolio_manager.traders.new(trader_params)

    respond_to do |format|
      if @trader.save
        format.html do
          redirect_to portfolio_manager_url(@portfolio_manager), notice: 'Trader was successfully created.'
        end
        # format.json { render :show, status: :created, location: @trader }
      else
        format.html { render :new, status: :unprocessable_entity }
        # format.json { render json: @trader.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /traders/1 or /traders/1.json
  def update
    # @admin = PortfolioManager.find(params[:portfolio_manager_id])
    @trader = @portfolio_manager.traders.find(params[:id])
    respond_to do |format|
      if @trader.update(trader_params)
        format.html do
          redirect_to portfolio_manager_url(@portfolio_manager), notice: 'Trader was successfully updated.'
        end
        # format.json { render :show, status: :ok, location: @trader }
      else
        format.html { render :edit, status: :unprocessable_entity }
        # format.json { render json: @trader.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /traders/1 or /traders/1.json
  def destroy
    # @admin = PortfolioManager.find(params[:portfolio_manager_id])
    @trader = @portfolio_manager.traders.find(params[:id])
    @trader.destroy

    respond_to do |format|
      format.html do
        redirect_to portfolio_manager_url(@portfolio_manager), notice: 'Trader was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.

  def set_portfolio_manager
    @portfolio_manager = PortfolioManager.find(params[:portfolio_manager_id])
  end

  # def set_trader
  #   return unless params[:id].present?

  #   @trader = @portfolio_manager.traders.find(params[:id])
  # end

  # def set_portfolio_manager
  #   @portfolio_manager = PortfolioManager.find_by(params[:portfolio_manager_id])
  # end

  # Only allow a list of trusted parameters through.
  def trader_params
    params.require(:trader).permit(:first_name, :last_name, :email, :password, :balance, :portfolio_manager_id)
  end

  # def edit_trader_params
  #   params.require(:trader).permit(:id)
  # end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/not_authorized_helper.rb
module NotAuthorizedHelper
end

app/helpers/not_found_helper.rb
module NotFoundHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/trader_profile_helper.rb
module TraderProfileHelper
end

app/helpers/traders_helper.rb
module TradersHelper
end

app/helpers/trading_helper.rb
module TradingHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/trader/index.html.erb
<div class="container">
<h1>Trader#index</h1>
<p>Find me in app/views/trader/index.html.erb</p>

 <input type="symbol" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Search symbol" value="AAPL">
<br/>
 <h2>AAPL</h2>
 <h3><%=@close%></h3>
 <table class="table">
  <%# <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead> %>
  <tbody>
   <tr>     
      <td>Current price</td>
      <td>1231.3123</td>
    <tr>
    <tr>     
      <td>MarkdividendYield</td>
      <td>1231.3123</td>
    <tr>
      <td>marketCap</td>
      <td>312321</td>
    </tr>
    <tr>     
      <td>blablalba</td>
      <td>the Bird</td>
    </tr>
  </tbody>
</table>
</div>

app/views/traders/_admin_traders.html.erb
<p style="color: green"><%= notice %></p>

<h1>Traders!!</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col">Balance</th>
    </tr>
  </thead>
  <tbody>   
    <% @administrator.traders.each do |trader| %>

      <%= render trader %>    
 
    <% end %>   
  </tbody>
</table>
 

<%= link_to "New trader", new_administrator_trader_path(@administrator) %>

app/views/traders/_form.html.erb
<%= form_for([@portfolio_manager, @trader]) do |form| %>
  <% if  @trader.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize( @trader.errors.count, "error") %> prohibited this trader from being saved:</h2>
      <ul>
        <%  @trader.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="p-2 d-flex flex-column">
    <div class="form-group">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, class:"form-control",placeholder:"First name"  %>
    </div>
    <div class="form-group">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, class:"form-control",placeholder:"Last name"  %>
    </div>
    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, class:"form-control",placeholder:"Emails"  %>
    </div>
    <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, class:"form-control",placeholder:"Password"  %>
    </div>
    <div class="form-group">
      <%= form.label :balance%>
      <%= form.text_field :balance, class:"form-control",placeholder:"Balance" %>
    </div>
    <div class="d-flex flex-row">
      <% if isAdmin %>
        <div class="p-2 form-group">
          <%= link_to "Cancel", @portfolio_manager , class:"btn btn-secondary"%>
        </div>
      <% end %>
      <div class="p-2 form-group">
        <%= form.submit :Submit, :value => "Save", class:"btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/traders/_portfolio_managers_traders.html.erb
<h2>Traders</h2>
<%= link_to "Add new", new_portfolio_manager_trader_path(@portfolio_manager),  class: "btn btn-primary" %>
<table class="mt-2 table">
  <thead>
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col">Balance</th>
      <th scope="col">Command</th>
    </tr>
  </thead>
  <tbody>
    <% @portfolio_manager.traders.each do |trader| %>
      <%= render trader %>
    <% end %>
  </tbody>
</table>

app/views/traders/_trader.html.erb
<tr>
  <td><%= trader.first_name %></td>
  <td><%= trader.last_name %></td>
  <td><%= trader.email %></td>
  <td><%= trader.balance %></td>
  <td>
    <div>
      <%= link_to 'Edit', edit_portfolio_manager_trader_path(trader.portfolio_manager, trader),  class: "btn btn-outline-primary" %>
      <%= link_to "Remove",[trader.portfolio_manager, trader], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                },   class: "btn btn-outline-danger" %>
    </div>
  </td>
</tr>

app/views/traders/edit.html.erb
<h1>Editing trader</h1>
<%= form_for([@trader.portfolio_manager, @trader]) do |form| %>
 <% if  @trader.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize( @trader.errors.count, "error") %> prohibited this trader from being saved:</h2>
      <ul>
        <%  @trader.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="p-2 d-flex flex-column">
    <div class="form-group">
      <%= form.label :first_name%>
      <%= form.text_field :first_name, class:"form-control",placeholder:"First name" %>
    </div>
    <div class="form-group">
      <%= form.label :last_name%>
      <%= form.text_field :last_name, class:"form-control",placeholder:"Last name" %>
    </div>
    <div class="form-group">
      <%= form.label :email%>
      <%= form.text_field :email, class:"form-control",placeholder:"Email" %>
    </div>
    <div class="form-group">
      <%= form.label :password%>
      <%= form.password_field :password, class:"form-control",placeholder:"Password" %>
    </div>
    <div class="form-group">
      <%= form.label :balance%>
      <%= form.text_field :balance, class:"form-control",placeholder:"Balance" %>
    </div>
    <div class="d-flex flex-row">
      <% if isAdmin %>
        <div class="p-2 form-group">
          <%= link_to "Cancel", @trader.portfolio_manager , class:"btn btn-secondary"%>
        </div>
      <% end %>
      <div class="p-2 form-group">
        <%= form.submit :Submit, :value => "Save", class:"btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/traders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Traders</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col">Balance</th>
      <th scope="col">Command</th>
    </tr>
  </thead>
  <tbody>   
    <% @traders.each do |trader| %>

      <%= render trader %>    
 
    <% end %>   
  </tbody>
</table>
 

<%= link_to "New trader", new_portfolio_manager_trader_path(@portfolio_manager) %>

app/views/traders/new.html.erb
<h1>New trader</h1>

<%= render "form"%>

app/views/traders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @trader %>

<div>
  <%= link_to "Edit this trader", edit_trader_path(@trader) %> |
  <%# <%= link_to "Back to traders", traders_path %> %>

  <%= button_to "Destroy this trader", @trader, method: :delete %>
</div>