config/routes.rb
Rails.application.routes.draw do
  get 'not_found/index'
  get 'administrator_profile/index'
  patch 'administrator_profile/update'
  get 'portfolio_manager_profile/index'
  patch 'portfolio_manager_profile/update'
  get 'trader_profile/index'
  patch 'trader_profile/update'
  get 'welcome/index'
  root 'welcome#index'
  get 'not_authorized/index'
  # resources :portfolio_managers
  resources :administrators

  post 'sessions/create'
  get 'sessions/destroy'

  get 'trading/index'
  get 'trading/autocomplete/:q', to: 'trading#autocomplete_symbol'
  get 'trading/getIntraPrices', to: 'trading#getIntraPrices'
  post 'trading/addFavoriteStock', to: 'trading#add_favorite_stock', via: :post, as: :add_favorite_stock
  post 'trading/removeFavoriteStock', to: 'trading#remove_favorite_stock', via: :delete, as: :remove_favorite_stock

   # resources :traders
  # get 'traders/index'

  resources :sessions, only: %i[new create destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :portfolio_managers do
    resources :traders
  end
end

app/models/administrator.rb
class Administrator < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/intraday_price.rb
class IntradayPrice
    attr_accessor :date, :open, :high, :low, :close, :volume
end

app/models/pm_profile.rb
class PmProfile < ApplicationRecord
  belongs_to :user
  
  validates :investment_strategy, length: { maximum: 50 }
  validates :ips, length: { maximum: 50 }
  validates :pm_notes, length: { maximum: 300 }  
end

app/models/portfolio_manager.rb
class PortfolioManager < User
end

app/models/service_result.rb
class ServiceResult
  attr_reader :succeeded, :errorMessage, :data

  def initialize(succeeded, errorMessage)
    @succeeded = succeeded
    @errorMessage = errorMessage
  end

  def initialize(succeeded)
    @succeeded = succeeded
  end

  def initialize; end

  def setAsSuccessful(data)
    @succeeded = true
    @data = data
    return self
  end

  def setAsFailed(errorMessage)
    @succeeded = false
    @errorMessage = errorMessage
    return self
  end
end

app/models/stock_price_info.rb
class StockPriceInfo
    attr_accessor :close, :dividends, :high, :low, :open, :stockSplits, :volume,
    :previousClose, :marketCap, :peRatio, :epsRatio, :dividendYield, :lastDividendValue, :averageVolume, :bid, :ask, :yield
end

app/models/stock_symbol.rb
class StockSymbol < ApplicationRecord
    has_many :trader_stocks, dependent: :destroy
    has_many :users, through: :trader_stocks
end

app/models/trader.rb
class Trader < User
 
end

app/models/trader_profile.rb
class TraderProfile < ApplicationRecord
  belongs_to :user

  validates :preferred_index1, length: { maximum: 50 }
  validates :preferred_index2, length: { maximum: 50 }
  validates :preferred_index3, length: { maximum: 50 }
  validates :trader_notes, length: { maximum: 300 }
end

app/models/trader_stock.rb
class TraderStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock_symbol
end

app/models/user.rb
class User < ApplicationRecord
  include PasswordValidable
  include UserFieldsValidable
  include AccountNameInitializable
  include UserProfileImageSeteable

  has_many :traders, class_name: 'Trader',
                     foreign_key: 'portfolio_manager_id',
                     dependent: :delete_all

  belongs_to :portfolio_manager, class_name: 'PortfolioManager', optional: true

  has_many :trader_stocks, dependent: :destroy
  has_many :stocks, through: :trader_stocks, source: :stock_symbol
  has_one :pm_profile, dependent: :destroy
  accepts_nested_attributes_for   :pm_profile
  has_one :trader_profile, dependent: :destroy
  accepts_nested_attributes_for :trader_profile
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_action do  verify_user_access("Administrator") end
  before_action :set_administrator, only: %i[ show edit update destroy ]

  # GET /administrators or /administrators.json
  def index
    @administrators = Administrator.all
  end

  # GET /administrators/1 or /administrators/1.json
  def show
  end

  # GET /administrators/new
  def new
    @administrator = Administrator.new
  end

  # GET /administrators/1/edit
  def edit
  end

  # POST /administrators or /administrators.json
  def create     
    @administrator = Administrator.new(administrator_params)
    
    respond_to do |format|
      if @administrator.save
        format.html { redirect_to administrators_url, notice: "Administrator was successfully created." }
        # format.json { render :show, status: :created, location: @administrator }
      else
        format.html { render :new, status: :unprocessable_entity }
        # format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrators/1 or /administrators/1.json
  def update
    respond_to do |format|
      if @administrator.update(administrator_params)
        format.html { redirect_to administrators_url, notice: "Administrator was successfully updated." }
        # format.json { render :show, status: :ok, location: @administrator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        # format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/1 or /administrators/1.json
  def destroy
    @administrator.destroy

    respond_to do |format|
      format.html { redirect_to administrators_url, notice: "Administrator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_administrator
     
      @administrator = Administrator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def administrator_params
      params.require(:administrator).permit(:first_name, :last_name, :email, :password)
    end
end

app/controllers/trader_controller.rb
class TraderController < ApplicationController
  def index
    require 'uri'
    require 'net/http'
    require 'openssl'
    
    url = URI(ENV["STOCK_PRICES_API_URL"])

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    request = Net::HTTP::Get.new(url)
    request["X-RapidAPI-Key"] = ENV["STOCK_PRICES_API_KEY"]
    request["X-RapidAPI-Host"] = ENV["STOCK_PRICES_API_HOST"]

    response = http.request(request)
    body = response.read_body   
    hash = JSON.parse(body)

    @close= hash[hash.keys[0]]["Close"]
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/not_authorized_helper.rb
module NotAuthorizedHelper
end

app/helpers/not_found_helper.rb
module NotFoundHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/traders_helper.rb
module TradersHelper
end

app/helpers/trading_helper.rb
module TradingHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/administrators/_administrator.html.erb
<div id="<%= dom_id administrator %>">
  <p>
    <strong>First name:</strong>
    <%= administrator.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= administrator.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= administrator.email %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= administrator.password %>
  </p>

</div>

app/views/administrators/_form.html.erb
<%= form_with(model: administrator) do |form| %>
  <% if administrator.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(administrator.errors.count, "error") %> prohibited this administrator from being saved:</h2>
      <ul>
        <% administrator.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="p-2 d-flex flex-column">
    <div class="form-group">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, class:"form-control",placeholder:"First name"  %>
    </div>
    <div class="form-group">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, class:"form-control",placeholder:"Last name" %>
    </div>
    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, class:"form-control",placeholder:"Emails" %>
    </div>
    <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, class:"form-control", placeholder:"Password" %>
    </div>
    <div class="d-flex flex-row">
      <div class="p-2 form-group">
        <%= link_to "Cancel", administrators_path , class:"btn btn-secondary"%>
      </div>
      <div class="p-2 form-group">
        <%= form.submit :Submit, :value => "Save", class:"btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/administrators/edit.html.erb
<h1>Editing administrator</h1>

<%= render "form", administrator: @administrator%>

app/views/administrators/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Administrators</h1>
<%= link_to "Add new", new_administrator_path,  class: "btn btn-primary" %>
<table class="table mt-2 ">
  <thead>
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @administrators.each do |administrator| %>
      <tr>
        <td><%= administrator.first_name %></td>
        <td><%= administrator.last_name %></td>
        <td><%= administrator.email %></td>
        <td>
          <div>
            <%= link_to 'Edit', edit_administrator_path(administrator), class: "btn btn-outline-primary" %>
            <%= link_to "Remove",[administrator], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                },   class: "btn btn-outline-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
 

app/views/administrators/new.html.erb
<h1>New administrator</h1>

<%= render "form", administrator: @administrator %>

app/views/administrators/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @administrator %>

<div>
  <%= link_to "Edit this administrator", edit_administrator_path(@administrator) %> |
  <%= link_to "Back to administrators", administrators_path %>

  <%= button_to "Destroy this administrator", @administrator, method: :delete %>
</div>