config/routes.rb
Rails.application.routes.draw do
  get 'not_found/index'
  get 'administrator_profile/index'
  patch 'administrator_profile/update'
  get 'portfolio_manager_profile/index'
  patch 'portfolio_manager_profile/update'
  get 'trader_profile/index'
  patch 'trader_profile/update'
  get 'welcome/index'
  root 'welcome#index'
  get 'not_authorized/index'
  # resources :portfolio_managers
  resources :administrators

  post 'sessions/create'
  get 'sessions/destroy'

  get 'trading/index'
  get 'trading/autocomplete/:q', to: 'trading#autocomplete_symbol'
  get 'trading/getIntraPrices', to: 'trading#getIntraPrices'
  post 'trading/addFavoriteStock', to: 'trading#add_favorite_stock', via: :post, as: :add_favorite_stock
  post 'trading/removeFavoriteStock', to: 'trading#remove_favorite_stock', via: :delete, as: :remove_favorite_stock

   # resources :traders
  # get 'traders/index'

  resources :sessions, only: %i[new create destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :portfolio_managers do
    resources :traders
  end
end

app/models/administrator.rb
class Administrator < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/intraday_price.rb
class IntradayPrice
    attr_accessor :date, :open, :high, :low, :close, :volume
end

app/models/pm_profile.rb
class PmProfile < ApplicationRecord
  belongs_to :user
  
  validates :investment_strategy, length: { maximum: 50 }
  validates :ips, length: { maximum: 50 }
  validates :pm_notes, length: { maximum: 300 }  
end

app/models/portfolio_manager.rb
class PortfolioManager < User
end

app/models/service_result.rb
class ServiceResult
  attr_reader :succeeded, :errorMessage, :data

  def initialize(succeeded, errorMessage)
    @succeeded = succeeded
    @errorMessage = errorMessage
  end

  def initialize(succeeded)
    @succeeded = succeeded
  end

  def initialize; end

  def setAsSuccessful(data)
    @succeeded = true
    @data = data
    return self
  end

  def setAsFailed(errorMessage)
    @succeeded = false
    @errorMessage = errorMessage
    return self
  end
end

app/models/stock_price_info.rb
class StockPriceInfo
    attr_accessor :close, :dividends, :high, :low, :open, :stockSplits, :volume,
    :previousClose, :marketCap, :peRatio, :epsRatio, :dividendYield, :lastDividendValue, :averageVolume, :bid, :ask, :yield
end

app/models/stock_symbol.rb
class StockSymbol < ApplicationRecord
    has_many :trader_stocks, dependent: :destroy
    has_many :users, through: :trader_stocks
end

app/models/trader.rb
class Trader < User
 
end

app/models/trader_profile.rb
class TraderProfile < ApplicationRecord
  belongs_to :user

  validates :preferred_index1, length: { maximum: 50 }
  validates :preferred_index2, length: { maximum: 50 }
  validates :preferred_index3, length: { maximum: 50 }
  validates :trader_notes, length: { maximum: 300 }
end

app/models/trader_stock.rb
class TraderStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock_symbol
end

app/models/user.rb
class User < ApplicationRecord
  include PasswordValidable
  include UserFieldsValidable
  include AccountNameInitializable
  include UserProfileImageSeteable

  has_many :traders, class_name: 'Trader',
                     foreign_key: 'portfolio_manager_id',
                     dependent: :delete_all

  belongs_to :portfolio_manager, class_name: 'PortfolioManager', optional: true

  has_many :trader_stocks, dependent: :destroy
  has_many :stocks, through: :trader_stocks, source: :stock_symbol
  has_one :pm_profile, dependent: :destroy
  accepts_nested_attributes_for   :pm_profile
  has_one :trader_profile, dependent: :destroy
  accepts_nested_attributes_for :trader_profile
end

app/controllers/trader_controller.rb
class TraderController < ApplicationController
  def index
    require 'uri'
    require 'net/http'
    require 'openssl'
    
    url = URI(ENV["STOCK_PRICES_API_URL"])

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    request = Net::HTTP::Get.new(url)
    request["X-RapidAPI-Key"] = ENV["STOCK_PRICES_API_KEY"]
    request["X-RapidAPI-Host"] = ENV["STOCK_PRICES_API_HOST"]

    response = http.request(request)
    body = response.read_body   
    hash = JSON.parse(body)

    @close= hash[hash.keys[0]]["Close"]
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/not_found_helper.rb
module NotFoundHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/traders_helper.rb
module TradersHelper
end

app/helpers/trading_helper.rb
module TradingHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <% if !logged_in? %>
        <a> <%= link_to 'TradingApp', welcome_index_path, class: "navbar-brand mb-0 h1" %> </a>
      <% end %>
      <% if logged_in? %>
        <% if isAdmin%>
          <a> <%= link_to 'TradingApp', administrators_path, class: "navbar-brand mb-0 h1" %> </a>
        <% end %>
        <% if isPortfolioManager%>
          <a> <%= link_to 'TradingApp', portfolio_manager_path(current_user.id), class: "navbar-brand mb-0 h1" %> </a>
        <% end %>
        <% if isTrader%>
          <a> <%= link_to 'TradingApp', trading_index_path, class: "navbar-brand mb-0 h1" %> </a>
        <% end %>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
          <% if logged_in? %>
            <% if isAdmin %>
              <li class="nav-item active">
                <%= link_to "Administrators", administrators_path, class: "nav-link"%>
              </li>
              <li class="nav-item active">
                <%= link_to "Portfolio Managers", portfolio_managers_path, class: "nav-link"%>
              </li>
            <% end %>
            <% if isPortfolioManager%>
              <li class="nav-item active">
                <%= link_to "Portfolio Manager", portfolio_manager_path(current_user.id), class: "nav-link"%>
              </li>
            <% end %>
            <% if isAdmin || isTrader%>
              <li class="nav-item active">
                <%= link_to "Trading", trading_index_path, class: "nav-link"%>
              </li>
            <% end %>
          <% end %>
        </ul>
        <% if !logged_in? %>
          <div>
            <%= link_to 'Sign In', welcome_index_path, class: "dropdown-item" %>
          </div>
        <% else %>
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link adropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false" style="padding: unset;">
                <%= "#{current_user.email}" %>
                <% if !current_user.profile_image.present? %>
                  <i class="fa-solid fa-user-tie fa-xl"></i>
                <% else %>
                  <img  src="<%= current_user.profile_image%>" class="aimg-fluid aprofile-thumbnail" style="width: 40px;
  height: 40px;
  box-sizing: border-box;
  background-clip: content-box;
  border: 2px solid transparent;
  border-radius: 49.9%;" />
                <% end %>
                <i class="fa-solid fa-caret-down"></i>
              </a>
              <div  class="dropdown-menu">
                <% if isAdmin %>
                  <a> <%= link_to 'Profile', administrator_profile_index_path, class: "dropdown-item" %> </a>
                <% end %>
                <% if isTrader %>
                  <a> <%= link_to 'Profile', trader_profile_index_path, class: "dropdown-item" %> </a>
                <% end %>
                <% if isPortfolioManager %>
                  <a> <%= link_to 'Profile', portfolio_manager_profile_index_path, class: "dropdown-item" %> </a>
                <% end %>
                <a> <%= link_to 'Logout', sessions_destroy_path, method: :delete, class: "dropdown-item" %> </a>
              </div>
            </div>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CloudProjectMH</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.11.1/typeahead.bundle.min.js" integrity="sha512-qOBWNAMfkz+vXXgbh0Wz7qYSLZp6c14R0bZeVX2TdQxWpuKr6yHjBIM69fcF8Ve4GUX6B6AKRQJqiiAmwvmUmQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_import_module_tag "@fortawesome/fontawesome-free" %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% if current_page?("/trading/index")  %>
      <div class="container" style="max-width: 1600px;">
      <% else %>
        <div class="container">
        <% end %>
        <%# <div class="container" style="max-width: 1600px;"> %>
        <%= yield %>
      </div>
    </body>
  </html>